name: Release Electron App

on:
  push:
    tags:
      - 'v*' # v1.0.0 のようなタグがpushされたら実行

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHubのPAT(Personal Access Token)を設定
          github_token: ${{ secrets.GH_TOKEN_FOR_RELEASE }}
          # 公開を実行
          release: true 